import React, { Component } from 'react'
import { Card } from 'react-bootstrap'
import { FaRobot } from 'react-icons/fa'
import {stopwords} from '../WordCloud/stopwords'

export default class ArtificialComments extends Component { 

  constructor(props) {
    super(props)
    this.state = {
      comments: []
    }
  }

  UNSAFE_componentWillMount(){
    if(this.props.comments.length>this.state.comments.length){
      this.setState({...this.props})
    }
  }

  getArtificialComments = () => {
    let words = {}
    this.props.comments.forEach(c => {
      const text = c.body
      const fixedText = text.replace(/(~|!|@|#|$|%|^|&|\*|\(|\)|{|}|\[|\]|;|:|'|'|<|,|\.|>|\?|\/|\\|\||-|_|\+|=)/g,'').toLowerCase().split(' ')
      fixedText.forEach(w => {
        if(stopwords.indexOf(w)===-1){
          if(! (w in words))
            words[w] = 0
          words[w]++
        }
      })
    })
    let data = []

    for(let w in words){
      data.push({'text': w, 'value': words[w]})
    }

    data = data.sort((a, b) => {return b.value-a.value})
    const body = {"subreddit":"nba","prefix":data[0].text,"key1":"","key2":"","key3":"","numtexts":"1"}

  }

  render() {
    return (
      <Card style={{marginTop: '2em'}}>
        <Card.Header>
          <FaRobot style={{marginRight: '10px'}} />
          Artificial Comments
        </Card.Header>
        <Card.Body>
          <h5>
            These are fake comments generated by a bot based on previous comments on the subreddit
          </h5>
          <p>
            {this.getArtificialComments()}
          </p>
        </Card.Body>
      </Card>
    )
  }
}
